import ts, { factory } from 'typescript';

const createGlobalObject = () =>
  factory.createVariableStatement(
    undefined,
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          factory.createIdentifier('getGlobalObject'),
          undefined,
          undefined,
          factory.createArrowFunction(
            undefined,
            [
              factory.createTypeParameterDeclaration(
                undefined,
                factory.createIdentifier('K'),
                factory.createTypeOperatorNode(
                  ts.SyntaxKind.KeyOfKeyword,
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Window'),
                    undefined,
                  ),
                ),
                undefined,
              ),
            ],
            [
              factory.createParameterDeclaration(
                undefined,
                undefined,
                factory.createIdentifier('name'),
                undefined,
                factory.createTypeReferenceNode(
                  factory.createIdentifier('K'),
                  undefined,
                ),
                undefined,
              ),
            ],
            factory.createIndexedAccessTypeNode(
              factory.createTypeReferenceNode(
                factory.createIdentifier('Window'),
                undefined,
              ),
              factory.createTypeReferenceNode(
                factory.createIdentifier('K'),
                undefined,
              ),
            ),
            factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
            factory.createElementAccessExpression(
              factory.createIdentifier('window'),
              factory.createIdentifier('name'),
            ),
          ),
        ),
      ],
      ts.NodeFlags.Const,
    ),
  );

const createGlobalFetch = () =>
  factory.createVariableStatement(
    undefined,
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          factory.createIdentifier('_globalFetch'),
          undefined,
          undefined,
          factory.createCallExpression(
            factory.createIdentifier('getGlobalObject'),
            undefined,
            [factory.createStringLiteral('fetch')],
          ),
        ),
      ],
      ts.NodeFlags.Const,
    ),
  );

const createDOMParser = () =>
  factory.createVariableStatement(
    undefined,
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          factory.createIdentifier('domParser'),
          undefined,
          undefined,
          factory.createNewExpression(
            factory.createIdentifier('DOMParser'),
            undefined,
            [],
          ),
        ),
      ],
      ts.NodeFlags.Const,
    ),
  );

const createRequest_ = () =>
  factory.createVariableStatement(
    undefined,
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          factory.createIdentifier('request'),
          undefined,
          undefined,
          factory.createArrowFunction(
            undefined,
            [
              factory.createTypeParameterDeclaration(
                undefined,
                factory.createIdentifier('T'),
                undefined,
                undefined,
              ),
            ],
            [
              factory.createParameterDeclaration(
                undefined,
                factory.createToken(ts.SyntaxKind.DotDotDotToken),
                factory.createArrayBindingPattern([
                  factory.createBindingElement(
                    undefined,
                    undefined,
                    factory.createIdentifier('input'),
                    undefined,
                  ),
                  factory.createBindingElement(
                    undefined,
                    undefined,
                    factory.createIdentifier('init'),
                    undefined,
                  ),
                  factory.createBindingElement(
                    factory.createToken(ts.SyntaxKind.DotDotDotToken),
                    undefined,
                    factory.createIdentifier('args'),
                    undefined,
                  ),
                ]),
                undefined,
                factory.createTupleTypeNode([
                  factory.createIndexedAccessTypeNode(
                    factory.createTypeReferenceNode(
                      factory.createIdentifier('Parameters'),
                      [
                        factory.createTypeQueryNode(
                          factory.createIdentifier('_globalFetch'),
                          undefined,
                        ),
                      ],
                    ),
                    factory.createLiteralTypeNode(
                      factory.createNumericLiteral('0'),
                    ),
                  ),
                  factory.createUnionTypeNode([
                    factory.createParenthesizedType(
                      factory.createIntersectionTypeNode([
                        factory.createIndexedAccessTypeNode(
                          factory.createTypeReferenceNode(
                            factory.createIdentifier('Parameters'),
                            [
                              factory.createTypeQueryNode(
                                factory.createIdentifier('_globalFetch'),
                                undefined,
                              ),
                            ],
                          ),
                          factory.createLiteralTypeNode(
                            factory.createNumericLiteral('1'),
                          ),
                        ),
                        factory.createTypeLiteralNode([
                          factory.createPropertySignature(
                            undefined,
                            factory.createIdentifier('data'),
                            factory.createToken(ts.SyntaxKind.QuestionToken),
                            factory.createTypeReferenceNode(
                              factory.createIdentifier('T'),
                              undefined,
                            ),
                          ),
                        ]),
                      ]),
                    ),
                    factory.createKeywordTypeNode(
                      ts.SyntaxKind.UndefinedKeyword,
                    ),
                  ]),
                ]),
                undefined,
              ),
            ],
            undefined,
            factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
            factory.createCallExpression(
              factory.createIdentifier('_globalFetch'),
              undefined,
              [
                factory.createIdentifier('input'),
                factory.createObjectLiteralExpression(
                  [
                    factory.createSpreadAssignment(
                      factory.createIdentifier('init'),
                    ),
                    factory.createPropertyAssignment(
                      factory.createIdentifier('headers'),
                      factory.createObjectLiteralExpression(
                        [
                          factory.createSpreadAssignment(
                            factory.createPropertyAccessChain(
                              factory.createIdentifier('init'),
                              factory.createToken(
                                ts.SyntaxKind.QuestionDotToken,
                              ),
                              factory.createIdentifier('headers'),
                            ),
                          ),
                          factory.createPropertyAssignment(
                            factory.createStringLiteral('Content-Type'),
                            factory.createStringLiteral('application/json'),
                          ),
                        ],
                        false,
                      ),
                    ),
                    factory.createPropertyAssignment(
                      factory.createIdentifier('body'),
                      factory.createConditionalExpression(
                        factory.createPropertyAccessChain(
                          factory.createIdentifier('init'),
                          factory.createToken(ts.SyntaxKind.QuestionDotToken),
                          factory.createIdentifier('data'),
                        ),
                        factory.createToken(ts.SyntaxKind.QuestionToken),
                        factory.createCallExpression(
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('JSON'),
                            factory.createIdentifier('stringify'),
                          ),
                          undefined,
                          [
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier('init'),
                              factory.createIdentifier('data'),
                            ),
                          ],
                        ),
                        factory.createToken(ts.SyntaxKind.ColonToken),
                        factory.createPropertyAccessChain(
                          factory.createIdentifier('init'),
                          factory.createToken(ts.SyntaxKind.QuestionDotToken),
                          factory.createIdentifier('body'),
                        ),
                      ),
                    ),
                  ],
                  true,
                ),
                factory.createSpreadElement(factory.createIdentifier('args')),
              ],
            ),
          ),
        ),
      ],
      ts.NodeFlags.Const,
    ),
  );

const createFetch = () =>
  factory.createVariableStatement(
    undefined,
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          factory.createIdentifier('fetch'),
          undefined,
          undefined,
          factory.createObjectLiteralExpression(
            [
              factory.createShorthandPropertyAssignment(
                factory.createIdentifier('request'),
                undefined,
              ),
              factory.createPropertyAssignment(
                factory.createIdentifier('json'),
                factory.createArrowFunction(
                  [factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                  [
                    factory.createTypeParameterDeclaration(
                      undefined,
                      factory.createIdentifier('T'),
                      undefined,
                      undefined,
                    ),
                  ],
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      factory.createToken(ts.SyntaxKind.DotDotDotToken),
                      factory.createIdentifier('args'),
                      undefined,
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('Parameters'),
                        [
                          factory.createTypeQueryNode(
                            factory.createIdentifier('request'),
                            undefined,
                          ),
                        ],
                      ),
                      undefined,
                    ),
                  ],
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Promise'),
                    [
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('T'),
                        undefined,
                      ),
                    ],
                  ),
                  factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier('fetch'),
                          factory.createIdentifier('request'),
                        ),
                        undefined,
                        [
                          factory.createSpreadElement(
                            factory.createIdentifier('args'),
                          ),
                        ],
                      ),
                      factory.createIdentifier('then'),
                    ),
                    undefined,
                    [
                      factory.createArrowFunction(
                        undefined,
                        undefined,
                        [
                          factory.createParameterDeclaration(
                            undefined,
                            undefined,
                            factory.createIdentifier('response'),
                            undefined,
                            factory.createTypeReferenceNode(
                              factory.createIdentifier('Response'),
                              undefined,
                            ),
                            undefined,
                          ),
                        ],
                        undefined,
                        factory.createToken(
                          ts.SyntaxKind.EqualsGreaterThanToken,
                        ),
                        factory.createCallExpression(
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('response'),
                            factory.createIdentifier('json'),
                          ),
                          undefined,
                          [],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              factory.createPropertyAssignment(
                factory.createIdentifier('text'),
                factory.createArrowFunction(
                  [factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                  undefined,
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      factory.createToken(ts.SyntaxKind.DotDotDotToken),
                      factory.createIdentifier('args'),
                      undefined,
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('Parameters'),
                        [
                          factory.createTypeQueryNode(
                            factory.createIdentifier('request'),
                            undefined,
                          ),
                        ],
                      ),
                      undefined,
                    ),
                  ],
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Promise'),
                    [
                      factory.createKeywordTypeNode(
                        ts.SyntaxKind.StringKeyword,
                      ),
                    ],
                  ),
                  factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier('fetch'),
                          factory.createIdentifier('request'),
                        ),
                        undefined,
                        [
                          factory.createSpreadElement(
                            factory.createIdentifier('args'),
                          ),
                        ],
                      ),
                      factory.createIdentifier('then'),
                    ),
                    undefined,
                    [
                      factory.createArrowFunction(
                        undefined,
                        undefined,
                        [
                          factory.createParameterDeclaration(
                            undefined,
                            undefined,
                            factory.createIdentifier('response'),
                            undefined,
                            factory.createTypeReferenceNode(
                              factory.createIdentifier('Response'),
                              undefined,
                            ),
                            undefined,
                          ),
                        ],
                        undefined,
                        factory.createToken(
                          ts.SyntaxKind.EqualsGreaterThanToken,
                        ),
                        factory.createCallExpression(
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('response'),
                            factory.createIdentifier('text'),
                          ),
                          undefined,
                          [],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              factory.createPropertyAssignment(
                factory.createIdentifier('html'),
                factory.createArrowFunction(
                  [factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                  undefined,
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      factory.createToken(ts.SyntaxKind.DotDotDotToken),
                      factory.createIdentifier('args'),
                      undefined,
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('Parameters'),
                        [
                          factory.createTypeQueryNode(
                            factory.createIdentifier('request'),
                            undefined,
                          ),
                        ],
                      ),
                      undefined,
                    ),
                  ],
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Promise'),
                    [
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('Document'),
                        undefined,
                      ),
                    ],
                  ),
                  factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier('fetch'),
                          factory.createIdentifier('text'),
                        ),
                        undefined,
                        [
                          factory.createSpreadElement(
                            factory.createIdentifier('args'),
                          ),
                        ],
                      ),
                      factory.createIdentifier('then'),
                    ),
                    undefined,
                    [
                      factory.createArrowFunction(
                        undefined,
                        undefined,
                        [
                          factory.createParameterDeclaration(
                            undefined,
                            undefined,
                            factory.createIdentifier('html'),
                            undefined,
                            factory.createKeywordTypeNode(
                              ts.SyntaxKind.StringKeyword,
                            ),
                            undefined,
                          ),
                        ],
                        undefined,
                        factory.createToken(
                          ts.SyntaxKind.EqualsGreaterThanToken,
                        ),
                        factory.createCallExpression(
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('domParser'),
                            factory.createIdentifier('parseFromString'),
                          ),
                          undefined,
                          [
                            factory.createIdentifier('html'),
                            factory.createStringLiteral('text/html'),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              factory.createPropertyAssignment(
                factory.createIdentifier('get'),
                factory.createArrowFunction(
                  [factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                  [
                    factory.createTypeParameterDeclaration(
                      undefined,
                      factory.createIdentifier('T'),
                      undefined,
                      undefined,
                    ),
                  ],
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      factory.createIdentifier('url'),
                      undefined,
                      factory.createUnionTypeNode([
                        factory.createKeywordTypeNode(
                          ts.SyntaxKind.StringKeyword,
                        ),
                        factory.createTypeReferenceNode(
                          factory.createIdentifier('URL'),
                          undefined,
                        ),
                      ]),
                      undefined,
                    ),
                  ],
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Promise'),
                    [
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('T'),
                        undefined,
                      ),
                    ],
                  ),
                  factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier('fetch'),
                      factory.createIdentifier('json'),
                    ),
                    undefined,
                    [
                      factory.createIdentifier('url'),
                      factory.createIdentifier('undefined'),
                    ],
                  ),
                ),
              ),
              factory.createPropertyAssignment(
                factory.createIdentifier('post'),
                factory.createArrowFunction(
                  [factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                  [
                    factory.createTypeParameterDeclaration(
                      undefined,
                      factory.createIdentifier('T'),
                      undefined,
                      undefined,
                    ),
                  ],
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      factory.createIdentifier('url'),
                      undefined,
                      factory.createUnionTypeNode([
                        factory.createKeywordTypeNode(
                          ts.SyntaxKind.StringKeyword,
                        ),
                        factory.createTypeReferenceNode(
                          factory.createIdentifier('URL'),
                          undefined,
                        ),
                      ]),
                      undefined,
                    ),
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      factory.createIdentifier('data'),
                      undefined,
                      factory.createKeywordTypeNode(
                        ts.SyntaxKind.UnknownKeyword,
                      ),
                      undefined,
                    ),
                  ],
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Promise'),
                    [
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('T'),
                        undefined,
                      ),
                    ],
                  ),
                  factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier('fetch'),
                      factory.createIdentifier('json'),
                    ),
                    undefined,
                    [
                      factory.createIdentifier('url'),
                      factory.createObjectLiteralExpression(
                        [
                          factory.createShorthandPropertyAssignment(
                            factory.createIdentifier('data'),
                            undefined,
                          ),
                        ],
                        false,
                      ),
                    ],
                  ),
                ),
              ),
              factory.createPropertyAssignment(
                factory.createIdentifier('put'),
                factory.createArrowFunction(
                  [factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                  [
                    factory.createTypeParameterDeclaration(
                      undefined,
                      factory.createIdentifier('T'),
                      undefined,
                      undefined,
                    ),
                  ],
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      factory.createIdentifier('url'),
                      undefined,
                      factory.createUnionTypeNode([
                        factory.createKeywordTypeNode(
                          ts.SyntaxKind.StringKeyword,
                        ),
                        factory.createTypeReferenceNode(
                          factory.createIdentifier('URL'),
                          undefined,
                        ),
                      ]),
                      undefined,
                    ),
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      factory.createIdentifier('data'),
                      undefined,
                      factory.createKeywordTypeNode(
                        ts.SyntaxKind.UnknownKeyword,
                      ),
                      undefined,
                    ),
                  ],
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Promise'),
                    [
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('T'),
                        undefined,
                      ),
                    ],
                  ),
                  factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier('fetch'),
                      factory.createIdentifier('json'),
                    ),
                    undefined,
                    [
                      factory.createIdentifier('url'),
                      factory.createObjectLiteralExpression(
                        [
                          factory.createShorthandPropertyAssignment(
                            factory.createIdentifier('data'),
                            undefined,
                          ),
                        ],
                        false,
                      ),
                    ],
                  ),
                ),
              ),
              factory.createPropertyAssignment(
                factory.createIdentifier('patch'),
                factory.createArrowFunction(
                  [factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                  [
                    factory.createTypeParameterDeclaration(
                      undefined,
                      factory.createIdentifier('T'),
                      undefined,
                      undefined,
                    ),
                  ],
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      factory.createIdentifier('url'),
                      undefined,
                      factory.createUnionTypeNode([
                        factory.createKeywordTypeNode(
                          ts.SyntaxKind.StringKeyword,
                        ),
                        factory.createTypeReferenceNode(
                          factory.createIdentifier('URL'),
                          undefined,
                        ),
                      ]),
                      undefined,
                    ),
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      factory.createIdentifier('data'),
                      undefined,
                      factory.createKeywordTypeNode(
                        ts.SyntaxKind.UnknownKeyword,
                      ),
                      undefined,
                    ),
                  ],
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Promise'),
                    [
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('T'),
                        undefined,
                      ),
                    ],
                  ),
                  factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier('fetch'),
                      factory.createIdentifier('json'),
                    ),
                    undefined,
                    [
                      factory.createIdentifier('url'),
                      factory.createObjectLiteralExpression(
                        [
                          factory.createShorthandPropertyAssignment(
                            factory.createIdentifier('data'),
                            undefined,
                          ),
                        ],
                        false,
                      ),
                    ],
                  ),
                ),
              ),
              factory.createPropertyAssignment(
                factory.createIdentifier('delete'),
                factory.createArrowFunction(
                  [factory.createToken(ts.SyntaxKind.AsyncKeyword)],
                  [
                    factory.createTypeParameterDeclaration(
                      undefined,
                      factory.createIdentifier('T'),
                      undefined,
                      undefined,
                    ),
                  ],
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      factory.createIdentifier('url'),
                      undefined,
                      factory.createUnionTypeNode([
                        factory.createKeywordTypeNode(
                          ts.SyntaxKind.StringKeyword,
                        ),
                        factory.createTypeReferenceNode(
                          factory.createIdentifier('URL'),
                          undefined,
                        ),
                      ]),
                      undefined,
                    ),
                  ],
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Promise'),
                    [
                      factory.createTypeReferenceNode(
                        factory.createIdentifier('T'),
                        undefined,
                      ),
                    ],
                  ),
                  factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                  factory.createCallExpression(
                    factory.createPropertyAccessExpression(
                      factory.createIdentifier('fetch'),
                      factory.createIdentifier('json'),
                    ),
                    undefined,
                    [
                      factory.createIdentifier('url'),
                      factory.createIdentifier('undefined'),
                    ],
                  ),
                ),
              ),
            ],
            false,
          ),
        ),
      ],
      ts.NodeFlags.Const,
    ),
  );

export const createRequest = () => [
  createGlobalObject(),
  createGlobalFetch(),
  createDOMParser(),
  createRequest_(),
  createFetch(),
];
